name: DevSecOps Pipeline

on:
  push:
  pull_request:

permissions:
  contents: read
  security-events: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

# ---------------- CODE QUALITY ----------------

jobs:

  code-quality:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install linters
        run: |
          pip install flake8 bandit

      - name: Lint check
        run: flake8 .

      - name: Security lint
        run: bandit -r .

# ---------------- DEPENDENCY SCAN ----------------

  dependency-scan:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        if: github.event_name == 'pull_request'

# ---------------- SECRET SCAN ----------------

  secrets-scan:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Secret scan
        uses: gitleaks/gitleaks-action@v2

# ---------------- DOCKERFILE LINT ----------------

  dockerfile-lint:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Dockerfile lint
        uses: hadolint/hadolint-action@v3
        continue-on-error: true

# ---------------- BUILD IMAGE ----------------

  build-image:

    needs:
      - code-quality
      - dependency-scan
      - secrets-scan
      - dockerfile-lint

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v3

        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build image

        run: |

          docker build -t \
          ${{ secrets.DOCKER_USERNAME }}/github-actions-capstone:latest .

      - name: Push image

        run: |

          docker push \
          ${{ secrets.DOCKER_USERNAME }}/github-actions-capstone:latest

# ---------------- IMAGE SCAN ----------------

  image-scan:

    needs: build-image

    runs-on: ubuntu-latest

    steps:

      - name: Scan container
        uses: aquasecurity/trivy-action@0.20.0

        with:
          image-ref: ${{ secrets.DOCKER_USERNAME }}/github-actions-capstone:latest
          severity: CRITICAL,HIGH

# ---------------- DEPLOY ----------------

  deploy:

    needs: image-scan

    runs-on: ubuntu-latest

    environment: production

    steps:

      - name: Deploy

        run: |

          echo "Deploying container"

          echo "${{ secrets.DOCKER_USERNAME }}/github-actions-capstone:latest"