name: Jobs Output Demo

on:
  push:

jobs:

  generate-date:
    runs-on: ubuntu-latest

    outputs:
      current_date: ${{ steps.date.outputs.today }}

    steps:
      - name: Generate Current Date
        id: date
        run: echo "today=$(date)" >> $GITHUB_OUTPUT

  use-date:
    runs-on: ubuntu-latest
    needs: generate-date

    steps:
      - name: Print Date from Previous Job
        run: echo "Date from previous job: ${{ needs.generate-date.outputs.today}}"