name: Multi-Job Pipeline

on:
  push: 

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Step
        run: echo "This is the build job."

  test:
      runs-on: ubuntu-latest
      - name: Test Step
        run: echo "This is the test job."  

  deploy:
      runs-on: ubuntu-latest
      - name: Deploy Step
        run: echo "This is the deploy job."