name: PR Validation

on:
  pull_request:
    branches:
      - main

jobs:

  file-size-check:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Check file size
        run: |
          find . -type f -size +1M && exit 1 || echo "All files OK"

  branch-name-check:

    runs-on: ubuntu-latest

    steps:

      - name: Check branch name
        run: |
          BRANCH=${{ github.head_ref }}

          if [[ "$BRANCH" == feature/* || "$BRANCH" == fix/* || "$BRANCH" == docs/* ]]
          then
            echo "Branch valid"
          else
            echo "Invalid branch name"
            exit 1
          fi

  pr-body-check:

    runs-on: ubuntu-latest

    steps:

      - name: Check PR description
        run: |
          if [ -z "${{ github.event.pull_request.body }}" ]
          then
            echo "Warning: PR description empty"
          else
            echo "PR description present"
          fi